name: Manual Build Twilight v2 with kernelsu For MI9SE(grus)

on:
  workflow_dispatch
   

jobs:
  TwilightForGrus:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y zip flex bison libncurses-dev gawk  libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full
          sudo apt clean
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date +%F)" >> $GITHUB_ENV
      - name: Cloning Sources and Toolchain
        run: |
          git clone https://github.com/kyasu/android_kernel_xiaomi_sdm710.git --depth=1 -b lineage-20 --recurse-submodules android_kernel_xiaomi_sdm710
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r445002 --depth=1 --single-branch --no-tags -b 12.0 ~/clang
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/aarch64-linux-android-4.9
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/arm-linux-androideabi-4.9
          git clone https://github.com/Tkiliay/AnyKernel3.git -b grus_kernelsu
      - name: Applying Kernel Patch
        run: |
           cd android_kernel_xiaomi_sdm710/KernelSU
           wget https://github.com/sticpaper/KernelSU-patch/commit/d2b6ef76772e62575904677e8118395ba3677820.patch
           patch -p1 < d2b6ef76772e62575904677e8118395ba3677820.patch
           rm -rf *.patch
      - name: Compiling Kernel
        run: |
          CLANG=~/clang/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          PATH=$CLANG:$GCC64:$GCC32:$PATH
          export PATH
          export ARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          output_dir=out
          pushd android_kernel_xiaomi_sdm710
          make O="$output_dir" \
                      sdm670-perf_defconfig \
                      xiaomi/sdm710-common.config \
                      xiaomi/grus.config
          make -j $(nproc) \
                       O="$output_dir" \
                       CC=clang
          popd
      - name: Packaging the Kernel
        run: |
          cp -v android_kernel_xiaomi_sdm710/out/arch/arm64/boot/Image.gz \
                     AnyKernel3/
          pushd AnyKernel3
          7z a -mx9 ../Twilight_KernelSU-V2-CI-${{ env.BUILD_TIME }}-grus-AOSP.zip *
          popd
      - name: Creating Config Info
        run: |
          echo "Device: MI 9 SE
          Code: Grus
          Build Code: ${{ github.run_number }}
          Twilight Kernel For MI9SE" >> INFO.txt
      - name: Uploading Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: Twilight_KernelSU-V2-CI-${{ env.BUILD_TIME }}-grus-AOSP.zip
          name: "Twilight_KernelSU-V2-grus_CI-${{ env.BUILD_TIME }}"
          tag: " ${{ env.BUILD_TIME }}_MI9SE_kernelsu-CI_${{ github.run_number }}"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}

